# -*- coding: utf-8 -*-
"""R1_drive_a_robot_with_rules.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19yRFxE7qL6ptRcIzyoqGikbl0QBXVcmU

# R1 — Drive a robot with rules you write yourself

**Level: never written code before. Time: about 2 hours. Nothing to install, no
account, no API key — this notebook does not even need the internet once it has
loaded.**

You are going to build the *brain* of a warehouse robot. It has three distance
sensors and a set of wheels, and it is looking for its charger.

By the end you will have written a brain that works, then watched it fail
completely on a different map, then worked out why. That failure is the point of
the whole session — it is the reason the other three notebooks exist.

> **This is preparation for the hackathon.** The commands your brain gives —
> `FORWARD`, `LEFT`, `RIGHT`, `STOP` — are exactly what you would send over a
> cable to an Arduino or a Raspberry Pi robot. The brain you write today is the
> brain you can bring next week.

---

### Run this first

The cell below is the robot's **body** — the simulated warehouse, the wheels,
the sensors. It is long, and **you never need to read or change it.** Everything
you write comes after it.

Click the cell and press **Shift+Enter**.

## code
"""

GRIDWORLD_SOURCE = r'''
"""
GridWorld - the shared robot simulator for Track C (AI in Robotics)
===================================================================

One robot. One grid. Four notebooks swap out its brain:

    R1  rules you write by hand          <- no AI at all
    R2  a pretrained vision model        <- computer vision
    R3  trained on your demonstrations   <- imitation learning
    R4  learned by trial and error       <- reinforcement learning

Every one of them writes the same function:

    def decide(sensors) -> "FORWARD" | "LEFT" | "RIGHT" | "STOP"

which is why moving up a level only ever changes one function.

WHY THE SENSORS LOOK LIKE THIS
------------------------------
A cheap Arduino robot car usually has three ultrasonic distance sensors -
one pointing forward, one left, one right - plus wheel encoders telling it
roughly where it is. So that is exactly what sense() gives you. The brain
you write here takes the same input a real robot would give it.
"""

import numpy as np

# Which way is which. Row 0 is the TOP of the grid, so going North means
# the row number gets SMALLER.
MOVES = {
    "N": (-1, 0),
    "E": (0, 1),
    "S": (1, 0),
    "W": (0, -1),
}

# Turning. Reading these in a circle: N -> E -> S -> W -> N is turning right.
RIGHT_TURN = {"N": "E", "E": "S", "S": "W", "W": "N"}
LEFT_TURN = {"N": "W", "W": "S", "S": "E", "E": "N"}

COMMANDS = ["FORWARD", "LEFT", "RIGHT", "STOP"]

# Things the robot cannot drive through. "wall" is a shelf; "object" is
# something sitting on the floor that R2's camera can take a picture of.
BLOCKED = ("wall", "object")

# What the characters in a layout mean.
#   #  shelf / wall - the robot cannot drive through it
#   .  empty floor
#   C  the charger - this is where the robot is trying to get to
#   R  where the robot starts (counts as empty floor)

# ---------------------------------------------------------------------------
# The maps
# ---------------------------------------------------------------------------

# A simple room. A basic "drive forward, turn at walls" rule solves this one.
FIRST_ROOM = [
    "#######",
    "#R....#",
    "#.###.#",
    "#....C#",
    "#######",
]

# The ring. This one looks easy and is NOT.
#
# A robot running "go forward, turn right at walls" drives round and round
# this loop forever. It passes right next to the charger on every single lap
# and never turns in, because nothing in that rule ever looks at the charger.
# That is the whole point of the map - see R1.
THE_RING = [
    "#########",
    "#R......#",
    "#.#####.#",
    "#.#####.#",
    "#.#####.#",
    "#.......#",
    "#####C###",
]

# A wider floor with scattered shelves, used by R3 and R4 where the robot
# needs somewhere with real choices to make.
WAREHOUSE = [
    "#########",
    "#R......#",
    "#.##.##.#",
    "#....#..#",
    "#.##...##",
    "#..##.#.#",
    "#.#....C#",
    "#########",
]

# An inspection lane for R2. The robot drives east down the corridor; six
# alcoves open off it to the right, each holding one object for the camera to
# look at. Deliberately simple - R2's difficulty should be in the vision, not
# in the navigation.
INSPECTION_LANE = [
    "#############",
    "#R.........C#",
    "#.#.#.#.#.#.#",
    "#############",
]

# R3 and R4 use these two. They are the same size and the same general idea -
# a depot with shelf blocks and a charger - but the shelves are in different
# places and the charger is at the other end. To a human they are obviously the
# same kind of building. To a copied policy they turn out not to be at all.
DEPOT = [
    "###########",
    "#C........#",
    "#.###.###.#",
    "#.........#",
    "#.###.###.#",
    "#R........#",
    "###########",
]

NEW_DEPOT = [
    "###########",
    "#........C#",
    "#.#####.#.#",
    "#.......#.#",
    "#.#####.#.#",
    "#R......#.#",
    "###########",
]

LAYOUTS = {
    "first_room": FIRST_ROOM,
    "ring": THE_RING,
    "warehouse": WAREHOUSE,
    "inspection_lane": INSPECTION_LANE,
    "depot": DEPOT,
    "new_depot": NEW_DEPOT,
}

# Where the alcoves are, left to right, for whoever is placing objects in them.
ALCOVES = [(2, 1), (2, 3), (2, 5), (2, 7), (2, 9), (2, 11)]


class GridWorld:
    """A robot on a grid of shelves, looking for its charger."""

    def __init__(self, layout="first_room", start_heading="E", objects=None):
        # objects: {(row, col): "some name"} - squares holding a real-world
        # thing. Blocked like a shelf, but the robot's camera can look at them.
        # R1 never uses this; R2 is built on it.
        self.objects = dict(objects or {})

        if isinstance(layout, str):
            if layout not in LAYOUTS:
                raise ValueError(
                    f"No layout called {layout!r}. "
                    f"Choose one of: {', '.join(LAYOUTS)}, or pass your own list of strings."
                )
            layout = LAYOUTS[layout]

        self.grid = [list(row) for row in layout]
        self.n_rows = len(self.grid)
        self.n_cols = len(self.grid[0])

        if any(len(row) != self.n_cols for row in self.grid):
            raise ValueError("Every row of the layout must be the same length.")

        self.start_heading = start_heading
        self._find_special_squares()
        self.reset()

    def _find_special_squares(self):
        self.start = None
        self.charger = None
        for r in range(self.n_rows):
            for c in range(self.n_cols):
                if self.grid[r][c] == "R":
                    self.start = (r, c)
                    self.grid[r][c] = "."     # R just marks the start; it is floor
                elif self.grid[r][c] == "C":
                    self.charger = (r, c)
        if self.start is None:
            raise ValueError("This layout has no 'R' marking where the robot starts.")
        if self.charger is None:
            raise ValueError("This layout has no 'C' marking the charger.")

    # -- running -----------------------------------------------------------

    def reset(self, start=None, heading=None):
        """Put the robot back at the beginning. Returns the first sensor reading."""
        self.row, self.col = start if start is not None else self.start
        self.heading = heading if heading is not None else self.start_heading
        self.steps = 0
        self.bumps = 0
        self.bumped = False
        self.trail = [(self.row, self.col)]
        return self.sense()

    def _what_is_at(self, row, col):
        """Describe one square the way a sensor would report it."""
        if not (0 <= row < self.n_rows and 0 <= col < self.n_cols):
            return "wall"
        if (row, col) in self.objects:
            return "object"
        square = self.grid[row][col]
        if square == "#":
            return "wall"
        if square == "C":
            return "charger"
        return "clear"

    def square_ahead(self, heading=None):
        """Which (row, col) is directly in front of the robot."""
        d_row, d_col = MOVES[heading or self.heading]
        return (self.row + d_row, self.col + d_col)

    def _square_in_direction(self, heading):
        return self._what_is_at(*self.square_ahead(heading))

    def sense(self):
        """What the robot can currently tell about the world.

        Returns a dictionary:
            front, left, right : "wall", "clear" or "charger"
            row, col, heading  : where it thinks it is (like wheel encoders)
            on_charger         : True once it has arrived
        """
        return {
            "front": self._square_in_direction(self.heading),
            "left": self._square_in_direction(LEFT_TURN[self.heading]),
            "right": self._square_in_direction(RIGHT_TURN[self.heading]),
            "row": self.row,
            "col": self.col,
            "heading": self.heading,
            "on_charger": self.on_charger(),
            # Name of the thing in each direction, or None. R2 turns these into
            # photographs and asks a vision model what it is looking at.
            "object_front": self.objects.get(self.square_ahead()),
            "object_left": self.objects.get(self.square_ahead(LEFT_TURN[self.heading])),
            "object_right": self.objects.get(self.square_ahead(RIGHT_TURN[self.heading])),
        }

    def on_charger(self):
        return (self.row, self.col) == self.charger

    def step(self, command):
        """Carry out one command. Returns the new sensor reading.

        FORWARD  drive one square the way you are facing (blocked by walls)
        LEFT     turn 90 degrees left, staying where you are
        RIGHT    turn 90 degrees right, staying where you are
        STOP     do nothing
        """
        if command not in COMMANDS:
            raise ValueError(
                f"{command!r} is not a command I understand.\n"
                f"Your decide() function must return one of: {', '.join(COMMANDS)}"
            )

        self.steps += 1
        self.bumped = False

        if command == "FORWARD":
            new_row, new_col = self.square_ahead()
            if self._what_is_at(new_row, new_col) in BLOCKED:
                # Drove into a shelf. A real robot would feel the bump and stop.
                self.bumped = True
                self.bumps += 1
            else:
                self.row, self.col = new_row, new_col
                self.trail.append((self.row, self.col))
        elif command == "LEFT":
            self.heading = LEFT_TURN[self.heading]
        elif command == "RIGHT":
            self.heading = RIGHT_TURN[self.heading]

        return self.sense()

    def run(self, brain, max_steps=60, animate=True, pause=0.15, verbose=False):
        """Let a brain drive until it reaches the charger or runs out of steps.

        `brain` is any function taking sensors and returning a command -
        which is exactly the decide() function you write in every notebook.

        Returns a small report dictionary so you can compare brains fairly.
        """
        sensors = self.reset()

        for _ in range(max_steps):
            if self.on_charger():
                break
            command = brain(sensors)
            sensors = self.step(command)
            if verbose:
                print(f"  step {self.steps:3}  at ({self.row},{self.col}) "
                      f"facing {self.heading}  -> {command}")
            if animate:
                self.render(pause=pause, clear=True)

        if animate:
            self.render(pause=0, clear=True)

        return {
            "reached_charger": self.on_charger(),
            "steps": self.steps,
            "bumps": self.bumps,
            "squares_visited": len(set(self.trail)),
        }

    # -- drawing -----------------------------------------------------------

    def render(self, pause=0.0, clear=False, title=None, ax=None):
        """Draw the grid. Shelves dark, floor light, charger green, robot an arrow."""
        import matplotlib.pyplot as plt

        if clear:
            from IPython.display import clear_output
            clear_output(wait=True)

        picture = np.zeros((self.n_rows, self.n_cols))
        for r in range(self.n_rows):
            for c in range(self.n_cols):
                if self.grid[r][c] == "#":
                    picture[r][c] = 0.15      # shelf
                elif self.grid[r][c] == "C":
                    picture[r][c] = 0.55      # charger
                else:
                    picture[r][c] = 1.0       # floor

        created = ax is None
        if created:
            fig, ax = plt.subplots(figsize=(1 + self.n_cols * 0.5,
                                            1 + self.n_rows * 0.5))

        ax.imshow(picture, cmap="Blues_r", vmin=0, vmax=1)

        # The path it has driven so far.
        if len(self.trail) > 1:
            rows = [p[0] for p in self.trail]
            cols = [p[1] for p in self.trail]
            ax.plot(cols, rows, color="tab:orange", linewidth=1.5,
                    alpha=0.6, zorder=2)

        ax.plot(self.charger[1], self.charger[0], marker="*", markersize=18,
                color="tab:green", zorder=3)

        # Things on the floor that R2's camera can photograph.
        for (obj_row, obj_col), name in self.objects.items():
            ax.plot(obj_col, obj_row, marker="s", markersize=15,
                    color="tab:purple", alpha=0.85, zorder=3)
            ax.text(obj_col, obj_row - 0.42, str(name)[:9], ha="center",
                    fontsize=6, color="tab:purple", zorder=5)

        arrow = {"N": "^", "E": ">", "S": "v", "W": "<"}[self.heading]
        ax.plot(self.col, self.row, marker=arrow, markersize=13,
                color="tab:red", zorder=4)

        if title is None:
            title = f"step {self.steps}"
            if self.on_charger():
                title += "  -  CHARGED!"
            elif self.bumped:
                title += "  -  bump!"
        ax.set_title(title, fontsize=10)
        ax.set_xticks([])
        ax.set_yticks([])

        if created:
            plt.show()
            plt.close(fig)          # or a long run leaves hundreds of figures open
        if pause:
            import time
            time.sleep(pause)


# ---------------------------------------------------------------------------
# The rule that fails, and the rule that works. R1 builds up to these.
# They live here so R2, R3 and R4 can import them for comparison.
# ---------------------------------------------------------------------------

def simple_brain(sensors):
    """Go forward. Turn right when something is in the way.

    Sensible-looking, and it solves 'first_room'. On 'ring' it drives in a
    circle forever, passing the charger on every lap - because not one line
    of it ever mentions the charger.
    """
    if sensors["front"] == "wall":
        return "RIGHT"
    return "FORWARD"


def charger_seeking_brain(sensors):
    """The same idea, but it actually looks for what it is searching for."""
    if sensors["left"] == "charger":
        return "LEFT"
    if sensors["right"] == "charger":
        return "RIGHT"
    if sensors["front"] == "wall":
        return "RIGHT"
    return "FORWARD"


def make_expert(world):
    """Build a brain that always takes a shortest path to the charger.

    It works by flood-filling outwards from the charger to find how many
    squares away every part of the floor is, then always stepping to a
    neighbour with a smaller number. This is a *planner*, not learning -
    it can only do this because it has been handed the whole map.

    R3 uses it as the demonstrator to copy. R4 uses it as the score to beat.
    """
    from collections import deque

    # How far is every square from the charger?
    distance = {world.charger: 0}
    queue = deque([world.charger])
    while queue:
        row, col = queue.popleft()
        for d_row, d_col in MOVES.values():
            neighbour = (row + d_row, col + d_col)
            if neighbour not in distance and world._what_is_at(*neighbour) not in BLOCKED:
                distance[neighbour] = distance[(row, col)] + 1
                queue.append(neighbour)

    def expert(sensors):
        here = (sensors["row"], sensors["col"])
        if here == world.charger:
            return "STOP"

        # Which way do we want to be facing? The neighbour closest to the charger.
        best_heading, best_distance = None, distance.get(here, 10**9)
        for heading, (d_row, d_col) in MOVES.items():
            neighbour = (here[0] + d_row, here[1] + d_col)
            if distance.get(neighbour, 10**9) < best_distance:
                best_distance = distance[neighbour]
                best_heading = heading

        if best_heading is None:
            return "STOP"                       # walled in - nothing to do
        if best_heading == sensors["heading"]:
            return "FORWARD"
        if best_heading == RIGHT_TURN[sensors["heading"]]:
            return "RIGHT"
        return "LEFT"                           # left, or a 180 - either way start turning

    return expert


# ---------------------------------------------------------------------------
# ON REAL HARDWARE
# ---------------------------------------------------------------------------
# Nothing above is specific to a simulation. Swap where the numbers come from
# and where the commands go, and the same decide() drives a real robot:
#
#     # in simulation
#     sensors = robot.sense()
#     robot.step(decide(sensors))
#
#     # on a Raspberry Pi / Arduino car, same brain
#     sensors = {"front": read_ultrasonic(TRIG_F, ECHO_F),
#                "left":  read_ultrasonic(TRIG_L, ECHO_L),
#                "right": read_ultrasonic(TRIG_R, ECHO_R)}
#     serial_port.write(decide(sensors).encode())
#
# This is why robotics teams build a simulator first: it is the same brain,
# but a crash costs nothing and you can run a thousand attempts a minute.
# ---------------------------------------------------------------------------

'''

# Save the robot's body next to this notebook, then load it.
with open('gridworld.py', 'w', encoding='utf-8') as f:
    f.write(GRIDWORLD_SOURCE)

from gridworld import GridWorld

print('Robot ready.')

"""---

## Part 1 — The warehouse ⏱ ~15 min

A map is just a **list of strings**. One string per row.

- `#` is a shelf. The robot cannot drive through it.
- `.` is empty floor.
- `R` is where the robot starts.
- `C` is the charger — where it is trying to get to.

A **list** in Python is written with square brackets, with commas between the
items. Read the map below like a picture and you can see the room.

"""

my_warehouse = [
    "#######",
    "#R....#",
    "#.###C#",
    "#.....#",
    "#.....#",
    "#######",
    "#######",
]

# A variable is just a name for something you want to keep.
# We made one called my_warehouse. Let's look at one row of it.
print(my_warehouse[1])

"""Python counts from **0**, not 1. So `my_warehouse[0]` is the top row of shelves
and `my_warehouse[1]` is the row the robot starts on.

Now let's actually see it.

"""

world = GridWorld(my_warehouse)
world.render()

"""The red arrow is the robot. It points the way the robot is facing — east, to
start with. The green star is the charger.

### ⏱ Your turn (3 min)

1. Print row `2` instead of row `1`.
2. Add another row of floor to `my_warehouse` (copy the `"#....C#"` line, change
   the `C` to a `.`, and put it above the charger row). Re-run both cells. Does
   the room get taller?
3. Move the `C` somewhere else and re-render.

> If you get `IndexError: list index out of range`, you asked for a row that
> does not exist. There are only 5 rows here, numbered 0 to 4.

---

## Part 2 — Making it move ⏱ ~15 min

The robot understands exactly four commands. You give one with `world.step(...)`:

| Command | What happens |
|---|---|
| `"FORWARD"` | drive one square the way you are facing |
| `"LEFT"` | turn 90° left, stay on the same square |
| `"RIGHT"` | turn 90° right, stay on the same square |
| `"STOP"` | do nothing |

The quote marks matter. `"FORWARD"` with quotes is a piece of **text**, which is
what the robot expects.
"""

world = GridWorld(my_warehouse)   # start over

world.step("FORWARD")
world.render()

"""It moved one square east. Run the cell below a few times in a row and watch it
travel — each time you run it, it takes one more step.

"""

world.step("FORWARD")
world.render()

"""Eventually it reaches the wall and stops moving — the title says **bump!**. A
real robot would have just driven into a shelf. Nothing is broken; it simply
cannot go through walls.

### ⏱ Your turn (5 min)

Starting from a fresh world, drive the robot to the charger **by hand**. You will
need to turn. Fill in the commands below — you need about 7 of them.

"""

world = GridWorld(my_warehouse)

world.step("FORWARD")
world.step("FORWARD")
world.step("FORWARD")
world.step("FORWARD")
world.step("RIGHT")
world.step("FORWARD")
world.render()
# ... your commands here. Add as many lines as you need.

world.render()
print("Made it?", world.on_charger())

"""That is *programming a robot*, and it works — but only for this exact room. Move
the charger and every line is wrong. That is what the rest of this notebook fixes.

---

## Part 3 — What the robot can feel ⏱ ~15 min

A real Arduino robot car usually has three ultrasonic distance sensors: one
pointing forward, one left, one right. Ours has the same three. Ask for a reading
with `world.sense()`.

"""

world = GridWorld(my_warehouse)
sensors = world.sense()
print(sensors)

"""That is a **dictionary** — a set of labelled values. You get one value out by
naming it in square brackets:

"""

print("in front of me:", sensors["front"])
print("to my left:      ", sensors["left"])
print("to my right:     ", sensors["right"])

"""Each of `front`, `left` and `right` is one of three words: `"wall"`, `"clear"`
or `"charger"`.

The dictionary also carries `row`, `col` and `heading` — the robot's rough idea
of where it is, like the wheel encoders on a real robot. You will not need those
until R3.

### ⏱ Your turn (5 min)

1. Turn the robot right, then sense again. Which readings changed?
2. Drive forward until `sensors["front"]` is `"wall"`, sensing as you go.
3. What do you think `sensors["front"]` says when the robot is facing the
   charger square? Guess first, then find out.

"""



"""---

## Part 4 — Your first brain ⏱ ~20 min

Here is the idea that makes it a robot instead of a list of instructions:

> **sense → think → act**, over and over.

The *think* part is a **function** — a named piece of code you can use again and
again. You write it with `def`:

"""

def decide(sensors):
    # If something is in the way, turn right. Otherwise drive on.
    if sensors["front"] == "wall":
        return "RIGHT"
    return "FORWARD"

"""Read that out loud: *"if the thing in front of me is a wall, turn right;
otherwise, go forward."* That is the entire brain.

Two bits of Python worth naming:

- `if ... :` runs the indented line underneath **only when** the test is true.
- `==` means *"is the same as"*. One `=` sets a value, two `==` asks a question.
  Mixing them up is the single most common beginner mistake in any language.
- `return` hands an answer back to whoever called the function.

Let's try it on one sensor reading before letting it drive:

"""

world = GridWorld(my_warehouse)
print("sensors say:", world.sense()["front"])
print("brain says: ", decide(world.sense()))

"""Now the sense-think-act loop. `for` repeats something a set number of times:

"""

world = GridWorld(my_warehouse)
sensors = world.sense()

for turn in range(10):          # do this up to 10 times
    if world.on_charger():
        break                   # stop early - we're there
    command = decide(sensors)   # THINK
    sensors = world.step(command)   # ACT (and sense again)

world.render()
print("Reached the charger?", world.on_charger())
print("Steps taken:", world.steps)

"""**It found the charger on its own.** Nobody told it where to go — it worked it
out from three sensor readings and two lines of rules.

The robot has a shortcut for that whole loop, which the rest of the notebook
uses. It does exactly what you just wrote:

"""

world = GridWorld(my_warehouse)
report = world.run(decide, max_steps=20, animate=True, pause=0.2)
print(report)

"""### ⏱ Your turn (7 min)

1. Change `decide` to turn **left** at walls instead of right. Does it still get
   there? Is it faster or slower?
2. What happens if `decide` always returns `"FORWARD"` and nothing else?
3. Make a brain that never moves at all. What does the report say?

---

## Part 5 — The map that defeats it ⏱ ~20 min

Your brain works. So let's put it in a different warehouse.

Same robot. Same brain. Not one character of `decide` changes.

"""

ring_world = GridWorld("ring")
ring_world.render()

"""A loop of corridor around a big block of shelves, with the charger tucked in a
gap at the bottom. Nothing exotic. Let's run the same brain.

*(We turn the animation off here — you will see why in a moment.)*

"""

ring_world = GridWorld("ring")
report = ring_world.run(decide, max_steps=60, animate=False)

ring_world.render(title="60 steps of your brain on the ring")
print(report)

"""**It never gets there.**

Look at the orange line: it is a *circle*. The report says 60 steps but only
about 20 different squares visited — it is going round and round the same loop.
Give it 60,000 steps and it would still be going.

And here is the part worth sitting with: **the charger is right next to the
path.** The robot drives past it, one square away, on every single lap.

### Why?

Read your brain out loud again:

> *"If the thing in front of me is a wall, turn right; otherwise, go forward."*

Now count how many times that sentence mentions the charger.

**Zero.** Your robot is not looking for the charger. It never was. It is just
driving forward and turning at walls, and on the first map that happened to
bump into the answer. It got the right result for the wrong reason.

This is the single most useful thing in this notebook. A rule that works is not
the same as a rule that is *right*, and the only way to tell them apart is to
try it somewhere new.

### ⏱ Your turn (5 min)

1. Run it with `max_steps=200`. Does more time help at all?
2. Try `animate=True, pause=0.1` and watch it lap. (Then turn it off again.)
3. Before you read on: what one thing would you add to `decide` to fix this?

---

## Part 6 — Fixing it ⏱ ~20 min

If the problem is that the brain never looks for the charger, the fix is to make
it look. The sensors already report `"charger"` — we have simply been ignoring it.

`elif` means *"else, if"*. Python checks each test top to bottom and runs the
**first** one that is true:
"""

def decide(sensors):
    if sensors["left"] == "charger":     # spotted it beside me - turn in
        return "LEFT"
    elif sensors["right"] == "charger":
        return "RIGHT"
    elif sensors["front"] == "wall":     # the old rule, still here
        return "RIGHT"
    else:
        return "FORWARD"

ring_world = GridWorld("ring")
report = ring_world.run(decide, max_steps=60, animate=True, pause=0.15)
print(report)

"""Two extra lines and it walks straight in.

Check it did not break the first map — a fix that breaks what already worked is
not a fix:

"""

for name in ["first_room", "ring"]:
    w = GridWorld(name)
    r = w.run(decide, max_steps=100, animate=False)
    print(f"{name:12} reached charger: {r['reached_charger']}   steps: {r['steps']}")

"""### The catch

Try that same brain on a bigger, messier floor:

"""

w = GridWorld("warehouse")
r = w.run(decide, max_steps=200, animate=False)
w.render(title="your brain on the warehouse floor")
print(r)

"""It fails again.

You could fix it. You would add an `elif`. Then a map appears where *that* fails,
and you add another. Every new situation is another line, and after twenty of
them nobody — including you — can say what the robot will do.

**This is the wall that every rule-based robot hits**, and it is exactly where
the next three notebooks pick up:

| | instead of writing rules… | |
|---|---|---|
| **R2** | let a **camera and an AI model** tell the robot what it is looking at | computer vision |
| **R3** | **show** the robot what to do and let it copy you | imitation learning |
| **R4** | let it **work it out itself** by trial and error | reinforcement learning |

All three keep the `decide(sensors)` function you just wrote. They only change
how it makes up its mind.

---

## Part 7 — On real hardware ⏱ ~10 min

Nothing you wrote today is about simulation. The brain takes sensor readings in
and gives commands out; it does not know or care where they come from.

```python
# what you did today
sensors = world.sense()
world.step(decide(sensors))

# the same brain, on a Raspberry Pi robot car
sensors = {"front": read_ultrasonic(TRIG_F, ECHO_F),
           "left":  read_ultrasonic(TRIG_L, ECHO_L),
           "right": read_ultrasonic(TRIG_R, ECHO_R)}
serial_port.write(decide(sensors).encode())
```

Two lines change. The thinking does not.

This is why robotics teams build a simulator first: same brain, but a crash
costs nothing and you can try a thousand runs in a minute instead of
recharging batteries and picking the robot up off the floor.

**For the hackathon:** get your robot driving on rules first, the way you did in
Part 4. It is the fastest thing to get working and it gives you something to
demo. Then make it smarter with R2, R3 or R4 — and when a judge asks why you
chose AI over rules, you will have Part 5 as your answer.

---

## What you learned

| Python | What it does |
|---|---|
| `x = 5` | a **variable** — a name for a value |
| `["a", "b"]` | a **list** — several things in order, counted from 0 |
| `d["front"]` | a **dictionary** — labelled values, fetched by name |
| `if` / `elif` / `else` | choose between options; the first true test wins |
| `==` | *is the same as* (not `=`, which sets a value) |
| `def name(x):` | a **function** — code you can name and reuse |
| `return` | hand an answer back |
| `for i in range(n):` | repeat something n times |

| Robotics | What it means |
|---|---|
| sense → think → act | the loop every robot runs, forever |
| `decide(sensors)` | the brain — swap it and you swap the robot's behaviour |
| the ring failure | working on one map is not the same as being correct |
| simulate first | crashes are free, and you can test a thousand times |

### If you have time

- Design a map that defeats the fixed brain in Part 6, and show it to someone.
- Write a brain that never bumps into anything, even if it never finds the
  charger. Which is more important for a real robot?
- Count the steps your brain takes on `first_room`. The best possible is 7. How
  close can you get on `ring`? (A perfect planner does it in 12.)

"""